### ISSUE TITLE
rf_hyperopt_train_test() Undefined 

### ISSUE THREAD

**Issue by alvinjeffery** [skparr/ml_loinc_mapping#1]
It doesn't look like this function is explicitly defined.  Is it up to the user to specify this? 

https://github.com/skparr/ml_loinc_mapping/blob/fcf273686578c38e2e141b5b000d82013cc69306/Analysis.py#L270

**Comment by skparr** [comment]
Haven’t gone through to clean up the code yet. I noticed that when I was working on manuscript revision that I think a cell accidentally got deleted maybe. Don’t have time to work on it this week, but thanks for bringing that to my attention!
